<?php

declare(strict_types=1);

namespace App\Enum;

enum CodeExceptionEnum: int
{
    case USER_CREATE_ERROR = 1001;
    case USER_EMAIL_INVALID = 1002;
    case USER_NOT_FOUND_ERROR = 1003;
    case USER_CREATE_NOT_AUTHORIZED = 1004;
    case USER_EMAIL_ALREADY_EXISTS = 1005;
    case USER_REQUIRED_FIELD_MISSING = 1006;
    case USER_IMPORT_VALIDATION_ERROR = 1007;
    case LOGIN_OR_PASSWORD_INVALID = 1008;


    case IMPORT_EMPTY_FILE = 2001;
    case IMPORT_INVALID_FILE = 2002;
    case IMPORT_INVALID_EXTENSION = 2003;
    case IMPORT_MISSING_HEADER = 2004;
    case IMPORT_ROW_ERROR = 2005;


    case EXPORT_EMPTY = 3001;
    case EXPORT_GENERAL_ERROR = 3002;


    case AGENDA_INVALID_DATE = 4001;
    case AGENDA_INVALID_ENUM = 4002;
    case AGENDA_INVALID_TIME_RANGE = 4003;
    case AGENDA_REQUIRED_FIELD_MISSING = 4004;
    case AGENDA_USER_NOT_FOUND = 4005;
}
